=== cragonnyunt/smart-movie-review/movielist/movielist.dtd
<!ELEMENT movies (movie+)>
<!ELEMENT movie (title,year,rating,poster,short,date,casts,directors,genres,companies,length,web,long_re,trailer)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT rating (imdb,rotten)>
<!ELEMENT poster (#PCDATA)>
<!ELEMENT short (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT casts (cast+)>
<!ELEMENT directors (director+)>
<!ELEMENT genres (genre+)>
<!ELEMENT companies (company+)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT long_re (#PCDATA)>
<!ELEMENT trailer (#PCDATA)>
<!ELEMENT imdb (#PCDATA)>
<!ELEMENT rotten (#PCDATA)>
<!ELEMENT cast (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT company (#PCDATA)>

=== cragonnyunt/smart-movie-review/movielist/movielist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movies SYSTEM "movielist.dtd">
<movies>
	<movie>
		<title>Batman Vs Superman: Dawn of Justice</title>
		<year>2016</year>
		<rating>
			<imdb>7.2</imdb>
			<rotten>28</rotten>
		</rating>
		<poster>movielist/poster/batman_v_superman_dawn_of_justice_2016_poster.jpg</poster>
		<short>Fearing that the actions of Superman are left unchecked, Batman takes on the Man of Steel, while the world wrestles with what kind of a hero it really needs. </short>
		<date>25 March 2016</date>
		<casts>
			<cast>Amy Adans</cast>
			<cast>Gal Gadot</cast>
			<cast>Ben Mffleck</cast>
		</casts>
		<directors>
			<director>Zack Snyder</director>
		</directors>
		<genres>
			<genre>Action</genre>
			<genre>Adventure</genre>
			<genre>Fantasy</genre>
		</genres>
		<companies>
			<company>Atlas Entertainment</company>
		</companies>
		<length>150</length>
		<web>http://www.facebook.com/batmanvsuperman</web>
		<long_re>Eighteen months after the destructive battle in Metropolis, Superman has become a controversial figure. Billionaire Bruce Wayne, who has covertly operated in Gotham City as vigilante Batman for nearly two decades, blames Superman for the mass casualties that resulted from his fight with General Zod. Superman, in his public identity as Daily Planet journalist Clark Kent, sees Batman as dangerous and seeks to expose him. </long_re>
		<trailer>movielist/trailers/batman_v_superman_dawn_of_justice_2016_trailer.mp4</trailer>
	</movie>
	<movie>
		<title>Captain America: Civil War</title>
		<year>2016</year>
		<rating>
			<imdb>8.2</imdb>
			<rotten>94</rotten>
		</rating>
		<poster>movielist/poster/captain_america_civil_war_2016_poster.jpg</poster>
		<short>Political interference in the Avengers' activities causes a rift between former allies Captain America and Iron Man. </short>
		<date>06 May 2016</date>
		<casts>
			<cast>Chris Evans</cast>
			<cast>Robert Downery Jr.</cast>
			<cast>Scarlett Johansson</cast>
			<cast>Sebastian Stan</cast>
		</casts>
		<directors>
			<director>Anthony russo</director>
			<director>Joe Russo</director>
		</directors>
		<genres>
			<genre>Action</genre>
			<genre>Adventure</genre>
			<genre>Sci-Fi</genre>
		</genres>
		<companies>
			<company>20th Century Fox</company>
		</companies>
		<length>147</length>
		<web>http://marvel.com/captainamerica#/home</web>
		<long_re>Marvel's  Captain America:Civil War finds Steve Rogers leading the newly formed team of Avengers in their continued efforts to safeguard humanity.But after another incident involving the Avengers results in collateral damage, political pressure mounts to install a system of accountability,headed by a governing body to oversee and direct the team. The new status quo fractures the Avengers, resulting in two camps-one led by Steve Rogers and his desire for the Avengers to remain free to defend humanity without government interference, and the other following Tony Stark's surprising decision to support government oversight and accountability. </long_re>
		<trailer>movielist/trailers/captain_america_civil_war_2016_trailer.mp4</trailer>
	</movie>
	<movie>
		<title>X-Men: Apocalypse</title>
		<year>2016</year>
		<rating>
			<imdb>7.4</imdb>
			<rotten>72</rotten>
		</rating>
		<poster>movielist/poster/xmen_apocalypse_2016_poster.jpg</poster>
		<short>With the emergence of the world's first mutant,Apocalypse,the X-Men must unite to defeat his extinction level plan. </short>
		<date>27 May 2016</date>
		<casts>
			<cast>James McAvoy</cast>
			<cast>Jennifer Lawrence</cast>
			<cast>Michael Fassbender</cast>
			<cast>Nicholas Hoult</cast>
		</casts>
		<directors>
			<director>Bryan Singer</director>
		</directors>
		<genres>
			<genre>Action</genre>
			<genre>Adventure</genre>
			<genre>Sci-Fi</genre>
		</genres>
		<companies>
			<company>20th Century Fox</company>
		</companies>
		<length>144</length>
		<web>http://www.foxmovies.com/movies/x-men-apocalypse</web>
		<long_re>Since the dawn of civilization, he was worshipped as God. Apocalypse, the first and most powerful mutant from Marvel's X-Men universe, amassed the powers of many other mutants, becoming the immortal and invinvible. Upon awakening after thousands of years, he is disillusioned with the world as he finds it and recurits a team of powerful mutants, including a dishearted Magneto, to cleanse mankind and create a new world order, over which he will reign. As the fate of the Earth hangs in the balance, Raven with the help of Professor X must lead a team of young X-Men to stop their greatest nemesis and save the mankind from complete destruction. </long_re>
		<trailer>movielist/trailers/xmen_apocalypse_2016_trailer.mp4</trailer>
	</movie>
	<movie>
		<title>The Other Side of the Door</title>
		<year>2016</year>
		<rating>
			<imdb>5.3</imdb>
			<rotten>37</rotten>
		</rating>
		<poster>movielist/poster/the_other_side_of_the_door_2016_poster.jpg</poster>
		<short>After her young son is killed in a tragic accident,a woman learns of a ritual which will bring him back to say goodbye, but when she disobeys a sacred warning,she upsets the balance between life and death. </short>
		<date>04 March 2016</date>
		<casts>
			<cast>Jeremy Sisto</cast>
			<cast>Logan Creran</cast>
			<cast>Sarah Wayne Callies</cast>
			<cast>Sofia Rosinsky</cast>
		</casts>
		<directors>
			<director>Rohannes Roberts</director>
		</directors>
		<genres>
			<genre>Horror</genre>
			<genre>Mystery</genre>
		</genres>
		<companies>
			<company>20th Century Fox</company>
		</companies>
		<length>96</length>
		<web>http://www.foxmovies.com/movies/the-other-side-of-the-door/</web>
		<long_re>A family lives an idyllic existence abroad until a tragic accident takes the life of their young son.The inconsolable mother learns of an ancient ritual that will bring him back to say a final goodbye.She travels to an ancient temple, where a door serves as a mysterious portal between two worlds.But when she disobeys a sacred warning to never open that door,she upsets the balance between life and death. </long_re>
		<trailer>movielist/trailers/the_other_side_of_the_door_2016_trailer.mp4</trailer>
	</movie>
	<movie>
		<title>London Has Fallen</title>
		<year>2016</year>
		<rating>
			<imdb>5.9</imdb>
			<rotten>62</rotten>
		</rating>
		<poster>movielist/poster/london_has_fallen_2016_poster.jpg</poster>
		<short>In London for the Prime Minister's funeral, Mike Banning discovers a plot to assassinate all the attending world leaders. </short>
		<date>04 March 2016</date>
		<casts>
			<cast>Gerard Butter</cast>
			<cast>Waleed Zuaiter</cast>
			<cast>Aaron Eckhart</cast>
			<cast>Morgan Freeman</cast>
		</casts>
		<directors>
			<director>Babak Najafi</director>
		</directors>
		<genres>
			<genre>Action</genre>
			<genre>Crime</genre>
			<genre>Thriller</genre>
		</genres>
		<companies>
			<company>Focus Features</company>
			<company>Lionsgate Films</company>
		</companies>
		<length>99</length>
		<web>http://www.londonhasfallen.com</web>
		<long_re>President Benjamin Asher and his top Secret Service agent/best friend Mike Banning are jogging together near the White House in Washington (which is still recovering from the terrorist attack in the previous film). Mike returns home where it is revealed that he is currently expecting his first child with his wife Leah. He is hoping to take some time off to spend time with his family and to finish setting up the nursery. She clearly becomes irritated by the number of securit cameras in the room that he has installed. </long_re>
		<trailer>movielist/trailers/london_has_fallen_2016_trailer.mp4</trailer>
	</movie>
	<movie>
		<title>Jungle Book</title>
		<year>2016</year>
		<rating>
			<imdb>7.8</imdb>
			<rotten>62</rotten>
		</rating>
		<poster>movielist/poster/jungle_book_2016_poster.jpg</poster>
		<short>The jungle experiences a very dry season, so the animals come together by the Peace Rock to form a truce and drink water from there. Mowgli uses the shell of a fruit to grab water for himself. </short>
		<date>15 April 2016</date>
		<casts>
			<cast>Ben Kihgsley</cast>
			<cast>Idris Elba</cast>
			<cast>Neel Sethi</cast>
			<cast>Bill Murray</cast>
			<cast>Sarah Finn</cast>
		</casts>
		<directors>
			<director>Jon Favreau</director>
		</directors>
		<genres>
			<genre>Adventure</genre>
			<genre>Drama</genre>
			<genre>Family</genre>
		</genres>
		<companies>
			<company>Walt Disney Pictures</company>
			<company>Lionsgate Films</company>
		</companies>
		<length>120</length>
		<web>http://movies.disney.com/the-jungle-book-2016</web>
		<long_re>After a threat from the tiger Shere Khan forces him to flee the jungle, a man-cub named Mowgli embarks on a journey of self discovery with the help of panther, Bagheera, and free spirited bear, Baloo. </long_re>
		<trailer>movielist/trailers/jungle_book_2016_trailer.mp4</trailer>
	</movie>
	<movie>
		<title>Deadpool</title>
		<year>2016</year>
		<rating>
			<imdb>8.2</imdb>
			<rotten>91</rotten>
		</rating>
		<poster>movielist/poster/deadpool_2016_poster.jpg</poster>
		<short>A former Special Forces operative turned mercenary is subjectid to a rogue experiment that leaves him with accelerated healing powers, adopting the alter ego Deadpool. </short>
		<date>12 February 2016</date>
		<casts>
			<cast>Ed Skrein</cast>
			<cast>Karan Soni</cast>
			<cast>Morena Baccarin</cast>
			<cast>Ryan Reynolds</cast>
		</casts>
		<directors>
			<director>Tim Miller</director>
		</directors>
		<genres>
			<genre>Adventure</genre>
			<genre>Action</genre>
			<genre>Comedy</genre>
		</genres>
		<companies>
			<company>20th Century Fox</company>
		</companies>
		<length>108</length>
		<web>http://www.foxmovies.com/movies/deadpool</web>
